      double precision autoang,autocmi
      integer maxatom,maxpair,maxdata,maxterm,maxperm,maxcoef
      parameter(autoang=0.529177249d0)
      parameter(autocmi=219474.63067d0)
      parameter(maxatom=8)	! max total atoms
      parameter(maxpair=28)	! max atom-atoms pairs
      parameter(maxdata=110000)	! max fitting data
      parameter(maxcoef=5000)	! max number of coefficients
      parameter(maxterm=80000)	! max number of polynomial terms
      parameter(maxperm=48+1)	! max number of symmetry permutations PLUS ONE???

